ncNodeMap =[{'atr':'collide',           'label': 'Collide',             'type': 'chb', 'min': 0,    'max': 1, 'hide': False},
         {'atr':'selfCollide',          'label': 'Self Collide',        'type': 'chb', 'min': 0,    'max': 1, 'hide': False},
         {'atr':'collisionFlag',        'label': 'Collision Flag',      'type': 'cmb', 'min': 0,    'max': 2, 'hide': False, 'enum': ['Vertex', 'Edge', 'Face']},
         {'atr':'selfCollisionFlag',    'label': 'Self Collision Flag', 'type': 'cmb', 'min': 0,    'max': 3, 'hide': False, 'enum': ['Vertex', 'Veertex Edge', 'Vertex Face', 'Full Surface']},
         {'atr':'collideStrength',      'label': 'Collide Strength',    'type': 'sld', 'min': 0,    'max': 1, 'hide': True},
         {'atr':'collisionLayer',       'label': 'Collision Layer',     'type': 'sld', 'min': 0,    'max': 10,'hide': True},
         {'atr':'thickness',            'label': 'Thickness',           'type': 'sld', 'min': 0,    'max': 3, 'hide': False},
         {'atr':'selfCollideWidthScale','label': 'Self Collide Width',  'type': 'sld', 'min': 0.01, 'max': 5, 'hide': False},
         {'atr':'solverDisplay',        'label': 'Solver Display',      'type': 'rb',  'min': 0,    'max': 5, 'hide': False, 'enum': ['Off', 'Collision', 'Srlf collision', 'Stretch Links', 'Bend Links', 'Weighting']},
         #{'atr':'displayColor',         'label': 'Display Color',       'type': 'sld', 'min': 0,    'max': 1, 'hide': True},
         {'atr':'bounce',               'label': 'Bounce',              'type': 'sld', 'min': 0,    'max': 1, 'hide': False},
         {'atr':'friction',             'label': 'Friction',            'type': 'sld', 'min': 0,    'max': 1, 'hide': False},
         {'atr':'stickiness',           'label': 'Stickiness',          'type': 'sld', 'min': 0,    'max': 2, 'hide': False},

         {'atr':'stretchResistance', 'label': 'Stretch', 'type': 'sld', 'min': 0, 'max': 200, 'hide': False},
         {'atr':'compressionResistance', 'label': 'Compression', 'type': 'sld', 'min': 0, 'max': 200, 'hide': False},
         {'atr':'bendAngleDropoff', 'label': 'Angle Dropoff', 'type': 'sld', 'min': 0, 'max': 1, 'hide': False},
         {'atr':'shearResistance', 'label': 'Shear', 'type': 'sld', 'min': 0, 'max': 200, 'hide': False},
         {'atr':'restitutionAngle', 'label': 'Restitution Angle', 'type': 'sld', 'min': 0, 'max': 360, 'hide': True},
         {'atr':'restitutionTension', 'label': 'Restitution Tension', 'type': 'sld', 'min': 0, 'max': 1000, 'hide': True},
         {'atr':'rigidity', 'label': 'Rigidity', 'type': 'sld', 'min': 0, 'max': 10, 'hide': True},
         {'atr':'deformResistance', 'label': 'Deform', 'type': 'sld', 'min': 0, 'max': 10, 'hide': True},
         {'atr':'usePolygonShells', 'label': 'Polygon Shells', 'type': 'chb', 'min': 0, 'max': 1, 'hide': True},
         {'atr':'inputMeshAttract', 'label': 'Input Attract', 'type': 'sld', 'min': 0, 'max': 1, 'hide': False},
         #{'atr':'inputAttractMethod', 'label': 'Input Method', 'type': 'cmb', 'min': 0, 'max': 1, 'hide': True},
         {'atr':'inputAttractDamp', 'label': 'Attract Damp', 'type': 'sld', 'min': 0, 'max': 1, 'hide': True},
         {'atr':'inputMotionDrag', 'label': 'Attract Motion Drag', 'type': 'sld', 'min': 0, 'max': 1, 'hide': True},
         {'atr':'restLengthScale', 'label': 'Rest Length Scale', 'type': 'sld', 'min': 0, 'max': 2, 'hide': True},
         {'atr':'bendAngleScale', 'label': 'Bend Scale', 'type': 'sld', 'min': -2, 'max': 2, 'hide': True},
         {'atr':'pointMass', 'label': 'Mass', 'type': 'sld', 'min': 0, 'max': 10, 'hide': False},
         {'atr':'lift', 'label': 'Lift', 'type': 'sld', 'min': 0, 'max': 0.2, 'hide': False},
         {'atr':'drag', 'label': 'Drag', 'type': 'sld', 'min': 0, 'max': 0.2, 'hide': False},
         {'atr':'tangentialDrag', 'label': 'Tangential Drag', 'type': 'sld', 'min': 0, 'max': 0.2, 'hide': False},
         {'atr':'damp', 'label': 'Damp', 'type': 'sld', 'min': 0, 'max': 10, 'hide': False},
         {'atr':'stretchDamp', 'label': 'Stretch Damp', 'type': 'sld', 'min': 0, 'max': 10, 'hide': True},
         {'atr':'ignoreSolverGravity', 'label': 'Ignore Gravity', 'type': 'chb', 'min': 0, 'max': 1, 'hide': False},
         {'atr':'ignoreSolverWind', 'label': 'Ignore Wind', 'type': 'sld', 'min': 0, 'max': 1, 'hide': True},
         {'atr':'pressure', 'label': 'Pressure', 'type': 'sld', 'min': -50, 'max': 50, 'hide': False},
         {'atr':'pushOut', 'label': 'Push Out', 'type': 'sld', 'min': -1, 'max': 1, 'hide': False},
         {'atr':'pushOutRadius', 'label': 'Push Out Radius', 'type': 'sld', 'min': 0, 'max': 100, 'hide': False}
         ]

